# Generated by Django 4.0.7 on 2022-09-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255)),
                ('limite_credito', models.FloatField(default=0.0)),
                ('apelido_cartao', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
