# Generated by Django 4.0.7 on 2022-09-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255)),
                ('id_cartao', models.BigIntegerField(serialize=False)),
                ('quantidade_parcelas', models.FloatField(default=1)),
                ('date', models.DateField()),
                ('tipo', models.CharField(default='outros', max_length=50)),
                ('nome', models.CharField(default='', max_length=50)),
                ('descricao', models.CharField(default='', max_length=150)),
                ('valor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='GastoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255)),
                ('date', models.DateField()),
                ('tipo', models.CharField(default='outros', max_length=50)),
                ('nome', models.CharField(default='', max_length=50)),
                ('descricao', models.CharField(default='', max_length=150)),
                ('valor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='GastoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255)),
                ('date', models.DateField()),
                ('tipo', models.CharField(default='outros', max_length=50)),
                ('nome', models.CharField(default='', max_length=50)),
                ('descricao', models.CharField(default='', max_length=150)),
                ('valor', models.FloatField(default=0.0)),
            ],
        ),
    ]
