version: "3"
services:
  api:
    container_name: api
    depends_on:
      - db
    restart: always
    build: ./
    command: "./start.sh"
    ports:
      - "8080:8080"
    env_file:
      - ./debug.env
      - ./.env
  db:
    container_name: db
    restart: always
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./debug.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
