version: '3'

services:
  api:
    container_name: api
    restart: always
    build: ./
    command: >
      sh -c "python manage.py flush --no-input &&
             python manage.py migrate &&
             DJANGO_SUPERUSER_PASSWORD=pass ./manage.py createsuperuser --no-input --email=leonardomichalskim@gmail.com &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    # volumes:
    #   - .:/core
